#!/bin/bash
# /etc/init.d/uwi

### BEGIN INIT INFO
# Provides:          uwi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UUGear Web Interface initialize script
# Description:       This service is used to manage UUGear Web Interface service
### END INIT INFO

case "$1" in
  start)
    echo "Starting UWI server..."
    . /home/pi/uwi/uwi.conf
    /home/pi/uwi/websocketd --address=$host --port=$port --staticdir=/home/pi/uwi /home/pi/uwi/messanger.sh &
    uwiPid=$(echo $!)
    logger "UWI server is started with pid=$uwiPid"
    echo $uwiPid > /var/run/uwi.pid
    ;;
  stop)
    echo "Stopping UWI server..."
    uwiPid=$(cat /var/run/uwi.pid)
    kill -9 $uwiPid
    ;;
  *)
    echo "Usage: /etc/init.d/uwi start|stop"
    exit 1
    ;;
esac

exit 0
